<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create a default user for companies
        $user = User::firstOrCreate(
            ['email' => 'employer@jobportal.test'],
            [
                'name' => 'Employer User',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ]
        );

        $companies = [
            [
                'user_id' => $user->id,
                'name' => 'TechCorp Solutions',
                'email' => 'careers@techcorp.com',
                'phone' => '+1 (555) 123-4567',
                'website' => 'https://techcorp.com',
                'about' => 'TechCorp Solutions is a leading technology company specializing in enterprise software solutions, cloud computing, and digital transformation services. We help businesses innovate and grow through cutting-edge technology.',
                'industry' => 'Technology',
                'location' => 'San Francisco, CA',
                'address' => '123 Tech Avenue',
                'city' => 'San Francisco',
                'state' => 'California',
                'country' => 'USA',
                'postal_code' => '94105',
                'employees_count' => 501,
                'founded_year' => 2010,
                'facebook_url' => 'https://facebook.com/techcorp',
                'twitter_url' => 'https://twitter.com/techcorp',
                'linkedin_url' => 'https://linkedin.com/company/techcorp',
                'instagram_url' => 'https://instagram.com/techcorp',
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'user_id' => $user->id,
                'name' => 'GreenEnergy Innovations',
                'email' => 'info@greenenergy.com',
                'phone' => '+1 (555) 234-5678',
                'website' => 'https://greenenergy.com',
                'about' => 'GreenEnergy Innovations is committed to developing sustainable energy solutions for a better tomorrow. We specialize in solar, wind, and renewable energy technologies that reduce carbon footprint.',
                'industry' => 'Energy',
                'location' => 'Denver, CO',
                'address' => '456 Green Street',
                'city' => 'Denver',
                'state' => 'Colorado',
                'country' => 'USA',
                'postal_code' => '80202',
                'employees_count' => 201,
                'founded_year' => 2015,
                'facebook_url' => 'https://facebook.com/greenenergy',
                'twitter_url' => 'https://twitter.com/greenenergy',
                'linkedin_url' => 'https://linkedin.com/company/greenenergy',
                'instagram_url' => 'https://instagram.com/greenenergy',
                'is_verified' => true,
                'is_active' => true,
            ],
            // [
            //     'user_id' => $user->id,
            //     'name' => 'MediCare Plus',
            //     'email' => 'hr@medicareplus.com',
            //     'phone' => '+1 (555) 345-6789',
            //     'website' => 'https://medicareplus.com',
            //     'about' => 'MediCare Plus is a premier healthcare provider offering comprehensive medical services, innovative treatments, and patient-centered care. Our mission is to improve lives through exceptional healthcare.',
            //     'industry' => 'Healthcare',
            //     'location' => 'Boston, MA',
            //     'address' => '789 Health Boulevard',
            //     'city' => 'Boston',
            //     'state' => 'Massachusetts',
            //     'country' => 'USA',
            //     'postal_code' => '02108',
            //     'employees_count' => 1001,
            //     'founded_year' => 2005,
            //     'facebook_url' => 'https://facebook.com/medicareplus',
            //     'twitter_url' => 'https://twitter.com/medicareplus',
            //     'linkedin_url' => 'https://linkedin.com/company/medicareplus',
            //     'instagram_url' => 'https://instagram.com/medicareplus',
            //     'is_verified' => true,
            //     'is_active' => true,
            // ],
            // [
            //     'user_id' => $user->id,
            //     'name' => 'FinanceFlow Advisors',
            //     'email' => 'careers@financeflow.com',
            //     'phone' => '+1 (555) 456-7890',
            //     'website' => 'https://financeflow.com',
            //     'about' => 'FinanceFlow Advisors provides expert financial consulting, investment management, and wealth planning services. We help individuals and businesses achieve their financial goals with strategic insights.',
            //     'industry' => 'Finance',
            //     'location' => 'New York, NY',
            //     'address' => '321 Wall Street',
            //     'city' => 'New York',
            //     'state' => 'New York',
            //     'country' => 'USA',
            //     'postal_code' => '10005',
            //     'employees_count' => 151,
            //     'founded_year' => 2012,
            //     'facebook_url' => 'https://facebook.com/financeflow',
            //     'twitter_url' => 'https://twitter.com/financeflow',
            //     'linkedin_url' => 'https://linkedin.com/company/financeflow',
            //     'instagram_url' => 'https://instagram.com/financeflow',
            //     'is_verified' => true,
            //     'is_active' => true,
            // ],
            // [
            //     'user_id' => $user->id,
            //     'name' => 'EduSmart Learning',
            //     'email' => 'jobs@edusmart.com',
            //     'phone' => '+1 (555) 567-8901',
            //     'website' => 'https://edusmart.com',
            //     'about' => 'EduSmart Learning is revolutionizing education through innovative learning platforms, digital content, and educational technology solutions. We make learning accessible and engaging for everyone.',
            //     'industry' => 'Education',
            //     'location' => 'Austin, TX',
            //     'address' => '654 Education Lane',
            //     'city' => 'Austin',
            //     'state' => 'Texas',
            //     'country' => 'USA',
            //     'postal_code' => '78701',
            //     'employees_count' => 89,
            //     'founded_year' => 2018,
            //     'facebook_url' => 'https://facebook.com/edusmart',
            //     'twitter_url' => 'https://twitter.com/edusmart',
            //     'linkedin_url' => 'https://linkedin.com/company/edusmart',
            //     'instagram_url' => 'https://instagram.com/edusmart',
            //     'is_verified' => false,
            //     'is_active' => true,
            // ],
            // [
            //     'user_id' => $user->id,
            //     'name' => 'RetailHub Stores',
            //     'email' => 'hr@retailhub.com',
            //     'phone' => '+1 (555) 678-9012',
            //     'website' => 'https://retailhub.com',
            //     'about' => 'RetailHub Stores operates a chain of modern retail outlets offering quality products at affordable prices. We are committed to providing excellent customer service and community engagement.',
            //     'industry' => 'Retail',
            //     'location' => 'Chicago, IL',
            //     'address' => '987 Market Street',
            //     'city' => 'Chicago',
            //     'state' => 'Illinois',
            //     'country' => 'USA',
            //     'postal_code' => '60601',
            //     'employees_count' => 301,
            //     'founded_year' => 2008,
            //     'facebook_url' => 'https://facebook.com/retailhub',
            //     'twitter_url' => 'https://twitter.com/retailhub',
            //     'linkedin_url' => 'https://linkedin.com/company/retailhub',
            //     'instagram_url' => 'https://instagram.com/retailhub',
            //     'is_verified' => true,
            //     'is_active' => true,
            // ],
            // [
            //     'user_id' => $user->id,
            //     'name' => 'BuildRight Construction',
            //     'email' => 'careers@buildright.com',
            //     'phone' => '+1 (555) 789-0123',
            //     'website' => 'https://buildright.com',
            //     'about' => 'BuildRight Construction specializes in commercial and residential construction projects. We are known for quality craftsmanship, timely delivery, and innovative building solutions.',
            //     'industry' => 'Construction',
            //     'location' => 'Miami, FL',
            //     'address' => '147 Builders Avenue',
            //     'city' => 'Miami',
            //     'state' => 'Florida',
            //     'country' => 'USA',
            //     'postal_code' => '33101',
            //     'employees_count' => 125,
            //     'founded_year' => 2014,
            //     'facebook_url' => 'https://facebook.com/buildright',
            //     'twitter_url' => 'https://twitter.com/buildright',
            //     'linkedin_url' => 'https://linkedin.com/company/buildright',
            //     'instagram_url' => 'https://instagram.com/buildright',
            //     'is_verified' => false,
            //     'is_active' => true,
            // ],
            // [
            //     'user_id' => $user->id,
            //     'name' => 'FoodDelight Restaurants',
            //     'email' => 'jobs@fooddelight.com',
            //     'phone' => '+1 (555) 890-1234',
            //     'website' => 'https://fooddelight.com',
            //     'about' => 'FoodDelight Restaurants offers exceptional dining experiences with a focus on quality ingredients, innovative recipes, and outstanding service. We operate multiple restaurant concepts across the region.',
            //     'industry' => 'Hospitality',
            //     'location' => 'Los Angeles, CA',
            //     'address' => '258 Food Court',
            //     'city' => 'Los Angeles',
            //     'state' => 'California',
            //     'country' => 'USA',
            //     'postal_code' => '90015',
            //     'employees_count' => 275,
            //     'founded_year' => 2016,
            //     'facebook_url' => 'https://facebook.com/fooddelight',
            //     'twitter_url' => 'https://twitter.com/fooddelight',
            //     'linkedin_url' => 'https://linkedin.com/company/fooddelight',
            //     'instagram_url' => 'https://instagram.com/fooddelight',
            //     'is_verified' => true,
            //     'is_active' => true,
            // ],
            // [
            //     'user_id' => $user->id,
            //     'name' => 'AutoMasters Group',
            //     'email' => 'recruitment@automasters.com',
            //     'phone' => '+1 (555) 901-2345',
            //     'website' => 'https://automasters.com',
            //     'about' => 'AutoMasters Group is a leading automotive company providing sales, service, and maintenance for various vehicle brands. We are committed to customer satisfaction and automotive excellence.',
            //     'industry' => 'Automotive',
            //     'location' => 'Detroit, MI',
            //     'address' => '369 Auto Plaza',
            //     'city' => 'Detroit',
            //     'state' => 'Michigan',
            //     'country' => 'USA',
            //     'postal_code' => '48201',
            //     'employees_count' => 189,
            //     'founded_year' => 2011,
            //     'facebook_url' => 'https://facebook.com/automasters',
            //     'twitter_url' => 'https://twitter.com/automasters',
            //     'linkedin_url' => 'https://linkedin.com/company/automasters',
            //     'instagram_url' => 'https://instagram.com/automasters',
            //     'is_verified' => true,
            //     'is_active' => true,
            // ],
            // [
            //     'user_id' => $user->id,
            //     'name' => 'CreativeMinds Agency',
            //     'email' => 'hello@creativeminds.com',
            //     'phone' => '+1 (555) 012-3456',
            //     'website' => 'https://creativeminds.com',
            //     'about' => 'CreativeMinds Agency is a full-service marketing and advertising agency that helps brands tell their stories through creative campaigns, digital marketing, and strategic branding.',
            //     'industry' => 'Marketing',
            //     'location' => 'Portland, OR',
            //     'address' => '741 Creative Lane',
            //     'city' => 'Portland',
            //     'state' => 'Oregon',
            //     'country' => 'USA',
            //     'postal_code' => '97205',
            //     'employees_count' => 67,
            //     'founded_year' => 2019,
            //     'facebook_url' => 'https://facebook.com/creativeminds',
            //     'twitter_url' => 'https://twitter.com/creativeminds',
            //     'linkedin_url' => 'https://linkedin.com/company/creativeminds',
            //     'instagram_url' => 'https://instagram.com/creativeminds',
            //     'is_verified' => false,
            //     'is_active' => true,
            // ]
        ];

        foreach ($companies as $company) {
            Company::create($company);
        }

        $this->command->info('Successfully seeded ' . count($companies) . ' companies.');
    }
}
